# Generated by Django 2.2.11 on 2020-06-07 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papertracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ['-id']},
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fullname', models.CharField(max_length=500)),
                ('year', models.IntegerField()),
                ('single', models.BooleanField(default=False)),
                ('double', models.BooleanField(default=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papertracker.Area')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papertracker.Organization')),
            ],
        ),
    ]
