# Generated by Django 2.2.11 on 2020-06-07 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papertracker', '0003_auto_20200607_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='category',
        ),
    ]
