# Generated by Django 2.2.11 on 2020-06-07 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papertracker', '0004_remove_conference_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
