# Generated by Django 2.2.11 on 2020-06-07 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papertracker', '0007_remove_conference_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='papertracker.Category'),
        ),
    ]
