# Generated by Django 2.2.11 on 2020-07-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papertracker', '0009_confauthor_confpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='unknown',
            field=models.BooleanField(default=False),
        ),
    ]
