# Generated by Django 2.2.11 on 2020-07-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papertracker', '0010_conference_unknown'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
