# Generated by Django 2.2.11 on 2020-07-17 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papertracker', '0011_cscat'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='cscat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='papertracker.CSCat'),
        ),
    ]
